name: Publish Package to PyPI (Test)

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: pip install -U setuptools wheel build
      - name: Build
        run: python -m build .
      - name: Test
        run: python -m unittest discover -v -s ./tests -p '*_test.py'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/
